### ISSUE TITLE
Implement a more efficient way of storing the sparse matrix

### ISSUE THREAD

**Issue by maxnth** [severinsimmler/word-embeddings#1]
Instead of using the defaultdicts "trick" we should use a more efficient data structure like the already available ones from scipy (scipy.sparse) or sklearn (sklearn.feature_extraction.DictVectorizer)

**Comment by severinsimmler** [comment]
Ref.: https://pandas.pydata.org/pandas-docs/stable/sparse.html#sparsedataframe

**Comment by maxnth** [comment]
Implemented using scipy.sparse and pd.SparseDataFrame.

**Comment by severinsimmler** [comment]
Fixed in https://github.com/severinsimmler/word-embeddings/commit/9555b003c7b34c3327107672029d167661ef3eeb 👍
